# Generated by Django 3.2.3 on 2021-06-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('author', models.CharField(max_length=32, unique=True)),
                ('year', models.PositiveSmallIntegerField(default=2000)),
                ('description', models.TextField(default='')),
                ('relise', models.DateField(blank=True, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plakaty')),
            ],
        ),
    ]
