# Generated by Django 3.2.3 on 2021-06-04 12:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wyporzyczalnia', '0002_auto_20210602_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Podaj typ książki (drama, horror etc)', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, null=True, verbose_name='ISBN'),
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('imprint', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, choices=[('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved'), ('u', 'Unknown')], default='u', help_text='Book status', max_length=1)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='wyporzyczalnia.book')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='bookgenre',
            field=models.ManyToManyField(to='wyporzyczalnia.BookGenre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(max_length=32, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wyporzyczalnia.author'),
        ),
    ]
