# Generated by Django 3.2.3 on 2021-06-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyporzyczalnia', '0003_auto_20210604_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, null=True, unique=True, verbose_name='ISBN'),
        ),
    ]
